title: Dustin Yoxall
description: Developer | IT Professional
baseurl: yoxalld.github.io

remote-theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  